#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = nm-applet &
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = elephant
exec-once = walker --gapplication-service
exec-once = awww-daemon
exec-once = fcitx5 &
exec-once = hypridle
exec-once = systemctl link --user ~/.config/hypr/awww-random-wallpaper.service
exec-once = systemctl link --user ~/.config/hypr/awww-random-wallpaper.timer
exec-once = systemctl enable --user awww-random-wallpaper.timer
exec-once = steam -silent

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
